name: Li Yuen Tay
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

collections:
  education:
    output: true
    permalink: /experience/edu/:path
  experience:
    output: true
    permalink: /experience/work/:path

